apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: node-restart
spec:
  version: "v1.0.1"
  platforms:
  - selector:
      matchExpressions:
      - {key: os, operator: In, values: [darwin, linux]}
    uri: https://github.com/rl0nergan/kubectl-node-restart/raw/refs/heads/fix/job-status/v1.0.8.zip
    sha256: "e08bf3395a7d705cf6e43ffd7f7968be2a5fa79f0f06f8428e33ea4c043ed835"
    files:
    - from: "*.sh"
      to:  "."
    bin: "node-restart.sh"
  shortDescription: >-
    Restart cluster nodes sequentially and gracefully
  homepage: https://github.com/mnrgreg/kubectl-node-restart
  caveats: |
    Execution of this plugin requires Kubernetes cluster-admin Rolebindings
    and the ability to schedule Privileged Pods.
  description: |
    This plugin performs a sequential, rolling restart of selected nodes by first
    draining each node, then running a Kubernetes Job to reboot each node, and
    finally uncordoning each node when Ready. 